### ISSUE TITLE
Error page template

### ISSUE THREAD

**Issue by mingard** [dadi/web#46]
Proposed config block
```JSON
"errorPage" : "workspace/pages/errors.dust"
```
Proposed template data format
```JSON
"error" : {
    "code" : ...,
    "msg" : ...,
    "line" : 12
}
```

**Comment by josephdenne** [comment]
Support for different templates for different error codes would be nice to have...

**Comment by jimlambie** [comment]
@josephdenne "codes" as in HTTP status codes? 4xx, 5xx etc?

**Comment by abovebored** [comment]
if you pass the error code `4xx, 5xx etc` to the page json we can keep contained to a single error.dust template

**Comment by jimlambie** [comment]
Yep, I was thinking along those lines.

**Comment by eduardoboucas** [comment]
We could support both approaches. When a `404` occurs, we first look for a `404.dust` and use that if it exists, otherwise use a general `error.dust`. In both cases we always pass the `error` object to the template.

If we think this is an overkill, a general `error.dust` should suffice, because we could do any routing necessary in the template itself (i.e. if `error.code` is `404`, render this partial, etc.).

**Comment by jimlambie** [comment]
@eduardoboucas the 404 case is already handled. If you have a 404.json and a 404.dust in your pages folder. Can receive data and run events like normal pages.

**Comment by eduardoboucas** [comment]
@jimlambie I just used 404 as an example, but the principle would apply for any error code (e.g. `500.dust`).
