### ISSUE TITLE
Error handling for incorrect redis session store

### ISSUE THREAD

**Issue by mdahlstrand** [dadi/web#75]
If the `sessions.store` redis url reference refers to a redis instance not reachable by dadi/web, the site won't start until it's tried restarting redis many times, causing a 10-60s delay on upstart, while at the same time not logging any errors.

Suggested solutions:

**A.** NodeRedis/node_redis which tj/connect-redis depends on exposes `connect_timeout` and `max_attempts`, both of which are deprecated but provide a quick and simple fix for the issue, where the server would return an error in case either limit is reached.

**B.** A more long term solution which doesn't use deprecated features could use the `retry_strategy` option as documented in the [readme of node_redis](https://github.com/NodeRedis/node_redis#rediscreateclient), but a conversation on what we want to do if redis is unavailable should be had. Quitting as soon as it doesn't work isn't a good idea, but having too many or too slow retries isn't good either. The readme linked just above provides an example, but since the dadi/web server is intended to run for long stretches of time another solution which ignores old disconnects and gets past temporary fluctuations in service availability should be implemented.

Implementing either solution would be done at https://github.com/dadi/web/blob/master/dadi/lib/index.js#L735

Questions:
Should each disconnect/failure to connect be logged?

**Comment by jimlambie** [comment]
I think option 2 is the sensible approach. If the cache fails to connect to Redis, it fails back to directory caching - so we *could* fallback to a memory store and log the error. 

I think the two cases this is an issue is 1) on start up with either incorrect config or Redis is in fact down, 2) when Redis becomes unreachable during normal operation (having already been connected at startup)

If 1) we should probably show the error in the console, and depending on the type of error decide what to do next (is config wrong, is the connection refused because Redis is down, etc)

If 2) we'd also need to periodically attempt to reconnect to Redis so the instance doesn't continue to use a memory store after Redis has become available.

Should each failure be logged? Probably the first one is enough, if it continues to retry we'd have the same error each time

**Comment by dark12222000** [comment]
Should we fail hard/entirely if redis is unavailable? My concern here is when redis is being used to handle user sessions - falling back to memory based storage would cause a lot of weird issues (as users are redirected to different instances by the outer ELB).

**Comment by jimlambie** [comment]
Consider the difference is errors here though, if Redis is unavailable for some reason during normal operation:

1. hard fail: 500 error -> "OMG what happened this site is totally down I can't do anything"
2. fallback: "oh I've been asked to sign again, that's weird."

:)

**Comment by dark12222000** [comment]
Wanted to attach some thoughts from Francesco, who pointed out:
+ AWS Redis is pretty unreliable
+ Often times when Redis fails it doesn't dc but just slows to a crawl

> in hindsight, the problems we had today are related to a malfunctioning Redis, which seems to be something not that rare from a quick look around AWS forums, ...we need to find ways to cater for a more unpredictable caching environment

>For example, when Redis was slow to respond, the toobusy kicked off, returning 503s to the LB very quickly (I understand the default is 70ms). 
This may be too drastic: if the Redis cache is slow, we could forget about it and fallback to file. I believe we do something similar if the connection to Redis is broken.

**Comment by jimlambie** [comment]
Closed by https://github.com/dadi/web/commit/857b099eec6435b225ba9a5d88b581cdac09f540
